### ISSUE TITLE
HTML exports

### ISSUE THREAD

**Issue by duckinator** [duckinator/how_is#13]
Implement HTML exports, with the Simple metrics (as defined in the [roadmap](https://github.com/duckinator/how_is/blob/master/roadmap.markdown)).

Prerequisite: #7 (Allow export to Ruby objects as well as files), because that will significantly affect the API for exporting things.

Metrics to include in HTML exports:

* [x] repository name
* [x] number of open issues
* [x] number of open PRs
* [x] number of issues associated with each label + no label
* [x] number of issues with no label
* [x] average issue age
* [x] average PR age
* [x] date oldest issue was opened
* [x] date oldest pull request was opened

This may be best done by creating a separate gem that behaves as a plugin of sorts for this one. E.g.,

```ruby
require 'how_is'
require 'how_is/report/html'

# ...
```

But the issue with that is how to tell the CLI executable to do `require 'how_is/report/html` for HTML exports. (But since we're only implementing HTML exports for a web service, which will be using how_is as a library, we can Handle That Later™.)

**Comment by duckinator** [comment]
![image](https://cloud.githubusercontent.com/assets/39698/16353273/156fb9a4-3a46-11e6-83b8-c6399e0367d4.png)

cc @LynnCo

**Comment by LynnCo** [comment]
👍👍👍👍👍👍👍👍👍👍

**Comment by duckinator** [comment]
Not quite right lol

![screenshot 37](https://cloud.githubusercontent.com/assets/39698/16353438/4feb4434-3a48-11e6-86fe-11d23ba0f544.png)

**Comment by duckinator** [comment]
Done.

![image](https://cloud.githubusercontent.com/assets/39698/16394078/7467a754-3c81-11e6-88f9-283b7b4e891f.png)
